# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing and Auto-merge

on: pull_request_target

env:
  CI: true

jobs:
  test_build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install
        run: pnpm install
        env:

      - name: Build
        run: pnpm build

      # for local testing only
      - name: Install local dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update
          apt-get -yqq install redis-server

      # for local testing only
      - name: Boot local dependencies
        if: ${{ env.ACT }}
        run: |
          service redis-server start

      - name: Test code
        run: pnpm test
        env:
          REDIS_HOST: redis

  auto-merge:
    needs: test_build

    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.SECRET }}
